keys:
  # TODO: Add your age public keys here.
  # Generate with:
  #   ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub
  # - &minecraft-server age1...
  # - &admin age1...
creation_rules:
  - path_regex: hosts/secrets.yaml$
    key_groups:
      - age:
        # - *minecraft-server
        # - *admin
