name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
            access-tokens = github.com=${{ github.token }}
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: nixfmt
        run: |
          nix profile install nixpkgs#nixfmt-rfc-style --impure
          nixfmt --check flake.nix hosts/comin.nix hosts/sops-base.nix \
            hosts/minecraft-server/configuration.nix \
            services/minecraft-server/default.nix

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
            access-tokens = github.com=${{ github.token }}
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build system closure
        run: |
          nix build .#nixosConfigurations.minecraft-server.config.system.build.toplevel \
            --no-link --print-out-paths 2>&1
